# Generated by Django 5.1.2 on 2024-10-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.CharField(verbose_name='Ссылка на картинку'),
        ),
    ]
